In [ ]:
from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score, precision_score, recall_score

In [ ]:
df = pd.read_csv("german_credit.csv")

In [ ]:
print(df.head())
print(df.info())

   Creditability  Account Balance  Duration of Credit (month)  \
0              1                1                          18
1              1                1                           9
2              1                2                          12
3              1                1                          12
4              1                1                          12

   Payment Status of Previous Credit  Purpose  Credit Amount  \
0                                  4        2           1049
1                                  4        0           2799
2                                  2        9            841
3                                  4        0           2122
4                                  4        0           2171

   Value Savings/Stocks  Length of current employment  Instalment per cent  \
0                     1                             2                    4
1                     1                             3                    2
2                     2                             4                    2
3                     1                             3                    3
4                     1                             3                    4

   Sex & Marital Status  ...  Duration in Current address  \
0                     2  ...                            4
1                     3  ...                            2
2                     2  ...                            4
3                     3  ...                            2
4                     3  ...                            4

   Most valuable available asset  Age (years)  Concurrent Credits  \
0                              2           21                   3
1                              1           36                   3
2                              1           23                   3
3                              1           39                   3
4                              2           38                   1

   Type of apartment  No of Credits at this Bank  Occupation  \
0                  1                           1           3
1                  1                           2           3
2                  1                           1           2
3                  1                           2           2
4                  2                           2           2

   No of dependents  Telephone  Foreign Worker
0                 1          1               1
1                 2          1               1
2                 1          1               1
3                 2          1               2
4                 1          1               2

[5 rows x 21 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Creditability                      1000 non-null   int64
 1   Account Balance                    1000 non-null   int64
 2   Duration of Credit (month)         1000 non-null   int64
 3   Payment Status of Previous Credit  1000 non-null   int64
 4   Purpose                            1000 non-null   int64
 5   Credit Amount                      1000 non-null   int64
 6   Value Savings/Stocks               1000 non-null   int64
 7   Length of current employment       1000 non-null   int64
 8   Instalment per cent                1000 non-null   int64
 9   Sex & Marital Status               1000 non-null   int64
 10  Guarantors                         1000 non-null   int64
 11  Duration in Current address        1000 non-null   int64
 12  Most valuable available asset      1000 non-null   int64
 13  Age (years)                        1000 non-null   int64
 14  Concurrent Credits                 1000 non-null   int64
 15  Type of apartment                  1000 non-null   int64
 16  No of Credits at this Bank         1000 non-null   int64
 17  Occupation                         1000 non-null   int64
 18  No of dependents                   1000 non-null   int64
 19  Telephone                          1000 non-null   int64
 20  Foreign Worker                     1000 non-null   int64
dtypes: int64(21)
memory usage: 164.2 KB
None

In [ ]:
print('Major Statistics',df.describe())

print("First 5 rows:")
print(df.head())

print("\nDataset Info:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

Major Statistics        Creditability  Account Balance  Duration of Credit (month)  \
count    1000.000000      1000.000000                 1000.000000
mean        0.700000         2.577000                   20.903000
std         0.458487         1.257638                   12.058814
min         0.000000         1.000000                    4.000000
25%         0.000000         1.000000                   12.000000
50%         1.000000         2.000000                   18.000000
75%         1.000000         4.000000                   24.000000
max         1.000000         4.000000                   72.000000

       Payment Status of Previous Credit      Purpose  Credit Amount  \
count                         1000.00000  1000.000000     1000.00000
mean                             2.54500     2.828000     3271.24800
std                              1.08312     2.744439     2822.75176
min                              0.00000     0.000000      250.00000
25%                              2.00000     1.000000     1365.50000
50%                              2.00000     2.000000     2319.50000
75%                              4.00000     3.000000     3972.25000
max                              4.00000    10.000000    18424.00000

       Value Savings/Stocks  Length of current employment  \
count           1000.000000                   1000.000000
mean               2.105000                      3.384000
std                1.580023                      1.208306
min                1.000000                      1.000000
25%                1.000000                      3.000000
50%                1.000000                      3.000000
75%                3.000000                      5.000000
max                5.000000                      5.000000

       Instalment per cent  Sex & Marital Status  ...  \
count          1000.000000            1000.00000  ...
mean              2.973000               2.68200  ...
std               1.118715               0.70808  ...
min               1.000000               1.00000  ...
25%               2.000000               2.00000  ...
50%               3.000000               3.00000  ...
75%               4.000000               3.00000  ...
max               4.000000               4.00000  ...

       Duration in Current address  Most valuable available asset  \
count                  1000.000000                    1000.000000
mean                      2.845000                       2.358000
std                       1.103718                       1.050209
min                       1.000000                       1.000000
25%                       2.000000                       1.000000
50%                       3.000000                       2.000000
75%                       4.000000                       3.000000
max                       4.000000                       4.000000

       Age (years)  Concurrent Credits  Type of apartment  \
count   1000.00000         1000.000000        1000.000000
mean      35.54200            2.675000           1.928000
std       11.35267            0.705601           0.530186
min       19.00000            1.000000           1.000000
25%       27.00000            3.000000           2.000000
50%       33.00000            3.000000           2.000000
75%       42.00000            3.000000           2.000000
max       75.00000            3.000000           3.000000

       No of Credits at this Bank   Occupation  No of dependents    Telephone  \
count                 1000.000000  1000.000000       1000.000000  1000.000000
mean                     1.407000     2.904000          1.155000     1.404000
std                      0.577654     0.653614          0.362086     0.490943
min                      1.000000     1.000000          1.000000     1.000000
25%                      1.000000     3.000000          1.000000     1.000000
50%                      1.000000     3.000000          1.000000     1.000000
75%                      2.000000     3.000000          1.000000     2.000000
max                      4.000000     4.000000          2.000000     2.000000

       Foreign Worker
count     1000.000000
mean         1.037000
std          0.188856
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          2.000000

[8 rows x 21 columns]
First 5 rows:
   Creditability  Account Balance  Duration of Credit (month)  \
0              1                1                          18
1              1                1                           9
2              1                2                          12
3              1                1                          12
4              1                1                          12

   Payment Status of Previous Credit  Purpose  Credit Amount  \
0                                  4        2           1049
1                                  4        0           2799
2                                  2        9            841
3                                  4        0           2122
4                                  4        0           2171

   Value Savings/Stocks  Length of current employment  Instalment per cent  \
0                     1                             2                    4
1                     1                             3                    2
2                     2                             4                    2
3                     1                             3                    3
4                     1                             3                    4

   Sex & Marital Status  ...  Duration in Current address  \
0                     2  ...                            4
1                     3  ...                            2
2                     2  ...                            4
3                     3  ...                            2
4                     3  ...                            4

   Most valuable available asset  Age (years)  Concurrent Credits  \
0                              2           21                   3
1                              1           36                   3
2                              1           23                   3
3                              1           39                   3
4                              2           38                   1

   Type of apartment  No of Credits at this Bank  Occupation  \
0                  1                           1           3
1                  1                           2           3
2                  1                           1           2
3                  1                           2           2
4                  2                           2           2

   No of dependents  Telephone  Foreign Worker
0                 1          1               1
1                 2          1               1
2                 1          1               1
3                 2          1               2
4                 1          1               2

[5 rows x 21 columns]

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Creditability                      1000 non-null   int64
 1   Account Balance                    1000 non-null   int64
 2   Duration of Credit (month)         1000 non-null   int64
 3   Payment Status of Previous Credit  1000 non-null   int64
 4   Purpose                            1000 non-null   int64
 5   Credit Amount                      1000 non-null   int64
 6   Value Savings/Stocks               1000 non-null   int64
 7   Length of current employment       1000 non-null   int64
 8   Instalment per cent                1000 non-null   int64
 9   Sex & Marital Status               1000 non-null   int64
 10  Guarantors                         1000 non-null   int64
 11  Duration in Current address        1000 non-null   int64
 12  Most valuable available asset      1000 non-null   int64
 13  Age (years)                        1000 non-null   int64
 14  Concurrent Credits                 1000 non-null   int64
 15  Type of apartment                  1000 non-null   int64
 16  No of Credits at this Bank         1000 non-null   int64
 17  Occupation                         1000 non-null   int64
 18  No of dependents                   1000 non-null   int64
 19  Telephone                          1000 non-null   int64
 20  Foreign Worker                     1000 non-null   int64
dtypes: int64(21)
memory usage: 164.2 KB
None

Missing Values:
Creditability                        0
Account Balance                      0
Duration of Credit (month)           0
Payment Status of Previous Credit    0
Purpose                              0
Credit Amount                        0
Value Savings/Stocks                 0
Length of current employment         0
Instalment per cent                  0
Sex & Marital Status                 0
Guarantors                           0
Duration in Current address          0
Most valuable available asset        0
Age (years)                          0
Concurrent Credits                   0
Type of apartment                    0
No of Credits at this Bank           0
Occupation                           0
No of dependents                     0
Telephone                            0
Foreign Worker                       0
dtype: int64